config/routes.rb
Sage::Application.routes.draw do

  resources :infos

  resources :solutions do
  end
  resources :services do
  end
  get "home/index"

  root :to => 'home#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :catalog, :content, :name
  validates :catalog, :presence => true
  validates :name, :presence => true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  USER_NAME, PASSWORD = "lrd", "lrd888"
  before_filter :authenticate, :except => [ :index,:show ]

  def index
    @services = Service.find(:all,:order =>"catalog")
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(params[:service])
    @service.save
    redirect_to services_path
  end

  def show
    @service = Service.find(params[:id])
    @services = Service.where("catalog = ?",@service.catalog)
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html  { redirect_to(@service, :notice => 'Successfully updated.') }
      end
    end
  end
  private
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password| 
      user_name == USER_NAME && password == PASSWORD
    end
  end
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/services/edit.html.slim
.form-horizontal
	= form_for @service do |f|
	  .control_group
		  .control_label= f.label :catalog, "Catalog"
		  .controls
		    .input-xlarge= f.text_field :catalog

		  .control_label= f.label :name ,"Name"
		  .controls
		    .input-xlarge= f.text_field :name

		  .control_label= f.label :content, "Content"
		  .controls
		    = f.kindeditor :content

	  .form-action
	    = f.submit "Update"

app/views/services/index.html.slim
- @cur_cat = ''
- @services.each do |f|
  - if @cur_cat == f.catalog
      li = f.name
      - @cur_cat = f.catalog
  - else
    h2 = f.catalog
    li = f.name
    - @cur_cat = f.catalog
br
.btn.btn-primary= link_to "New", new_service_path

app/views/services/new.html.slim
.form-horizontal
	= form_for @service do |f|
	  .control_group
		  .control_label= f.label :catalog, "Catalog"
		  .controls
		    .input-xlarge= f.text_field :catalog

		  .control_label= f.label :name ,"Name"
		  .controls
		    .input-xlarge= f.text_field :name

		  .control_label= f.label :content, "Content"
		  .controls
		    = f.kindeditor :content

	  .form-action
	    = f.submit "Create"

app/views/services/show.html.slim
h2 = @service.catalog
hr
.row
  .span9
    h5 = @service.name
    p = raw @service.content
  .span3
    .well
      - @services.each do |f|
        ul
          li
            = link_to f.name, service_path(f)