config/routes.rb
Sage::Application.routes.draw do

  resources :infos

  resources :solutions do
  end
  resources :services do
  end
  get "home/index"

  root :to => 'home#index'

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  attr_accessible :catalog, :content, :name
  validates :catalog, :presence => true
  validates :name, :presence => true
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  USER_NAME, PASSWORD = "lrd", "lrd888"
  before_filter :authenticate, :except => [ :index,:show ]

  def index
  	@solutions = Solution.find(:all,:order =>"catalog")
  end

  def new
  	@solution = Solution.new
  end
  
  def create
  	@solution = Solution.new(params[:solution])
  	@solution.save
  	redirect_to solutions_path
  end

  def show
    @solution = Solution.find(params[:id])
    @solutions = Solution.where("catalog = ?",@solution.catalog)
  end

  def edit
    @solution = Solution.find(params[:id])
  end

  def update
    @solution = Solution.find(params[:id])
    respond_to do |format|
      if @solution.update_attributes(params[:solution])
        format.html  { redirect_to(@solution, :notice => 'Successfully updated.') }
      end
    end
  end
  private
      def authenticate
          authenticate_or_request_with_http_basic do |user_name, password| 
          user_name == USER_NAME && password == PASSWORD
      end
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/edit.slim
.form-horizontal
	= form_for @solution do |f|
	  .control_group
		  .control_label= f.label :catalog, "Catalog"
		  .controls
		    .input-xlarge= f.text_field :catalog

		  .control_label= f.label :name ,"Name"
		  .controls
		    .input-xlarge= f.text_field :name

		  .control_label= f.label :content, "Content"
		  .controls
		    = f.kindeditor :content

	  .form-action
	    = f.submit "Update"

app/views/solutions/index.slim
- @cur_cat = ''
- @solutions.each do |f|
  - if @cur_cat == f.catalog
      li = f.name
      - @cur_cat = f.catalog
  - else
    h2 = f.catalog
    li = f.name
    - @cur_cat = f.catalog
br
.btn.btn-primary= link_to "New", new_solution_path


app/views/solutions/new.slim
.form-horizontal
	= form_for @solution do |f|
	  .control_group
		  .control_label= f.label :catalog, "Catalog"
		  .controls
		    .input-xlarge= f.text_field :catalog

		  .control_label= f.label :name ,"Name"
		  .controls
		    .input-xlarge= f.text_field :name

		  .control_label= f.label :content, "Content"
		  .controls
		    = f.kindeditor :content

	  .form-action
	    = f.submit "Create"

app/views/solutions/show.slim
h2 = @solution.catalog
hr
.row
  .span9
    h5 = @solution.name
    p = raw @solution.content
  .span3
    .well
      - @solutions.each do |f|
        ul
          li
            = link_to f.name, solution_path(f)