config/routes.rb
Sage::Application.routes.draw do

  resources :infos

  resources :solutions do
  end
  resources :services do
  end
  get "home/index"

  root :to => 'home#index'

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :content, :title, :zd
  validates :title, :presence => true
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  USER_NAME, PASSWORD = "lrd", "lrd888"
  before_filter :authenticate, :except => [ :index,:show ]
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])
    @infos = Info.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
  private
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password| 
      user_name == USER_NAME && password == PASSWORD
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.slim
= form_for @info do |f|
  - if @info.errors.any?
    #error_explanation
      h2 = "#{pluralize(@info.errors.count, "error")} prohibited this info from being saved:"
      ul
        - @info.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit 'Save'

app/views/infos/edit.html.slim
.form-horizontal
	= form_for @info do |f|
	  .control_group
		  .control_label= f.label :title ,"Title"
		  .controls
		    .input-xlarge= f.text_field :title
		  .control_label= f.label :zd ,"Zd"
		  .controls
		    .input-xlarge= f.text_field :zd
		  .control_label= f.label :content, "Content"
		  .controls
		    = f.kindeditor :content

	  .form-action
	    = f.submit "Update"

app/views/infos/index.html.slim
table
  - @infos.each do |info|
    tr
      td = link_to info.title, info_path(info)
      td = info.updated_at
      /td = info.content
      /td = link_to 'Show', info
      /td = link_to 'Edit', edit_info_path(info)
      /td = link_to 'Destroy', info, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Info', new_info_path

app/views/infos/new.html.slim
.form-horizontal
	= form_for @info do |f|
	  .control_group
		  .control_label= f.label :title ,"Title"
		  .controls
		    .input-xlarge= f.text_field :title

		  .control_label= f.label :content, "Content"
		  .controls
		    = f.kindeditor :content

	  .form-action
	    = f.submit "Create"

app/views/infos/show.html.slim
.span12
	.row
	  .span3
	    .well
	      - @infos.each do |f|
	        ul
	          li
	            = link_to f.title, info_path(f)
	  .span9
	    h3 align="center"  
	      = @info.title
	    p = raw @info.content